AWSTemplateFormatVersion: 2010-09-09
Description: This template is used to provision our dev network environment
Metadata: {}

Parameters: 
  vpcCidar:
    Description: This is the cidar for the dev vpc
    Type: String
    Default: 10.0.0.0/16

  devWebserverAz:
    Description: This is the availability zone for the developer webserver subnet
    Type: String
    Default: us-east-1a

  devWebserverSubnetCidar:
    Description: This is the cidar block for the dev webserver subnet
    Type: String
    Default: 10.0.1.0/24

Mappings: {}

Conditions: {}

Resources: 
  # Development vpc
  devVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref vpcCidar
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: devVPV

  # webserver subnet
  devWebserverSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref devWebserverAz
      VpcId: !Ref devVPC
      CidrBlock: !Ref devWebserverSubnetCidar
      Tags:
        - Key: Name
          Value: devWebserverSubnet

  # appserver subnet
  devAppserverSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref devVPC
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: devAppserverSubnet

  # dbserver subnet
  devDbserverSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref devVPC
      CidrBlock: 10.0.3.0/24
      Tags:
        - Key: Name
          Value: devDbserverSubnet

Outputs: {}